
# Create Keycloak DB in postgres
- hosts: console
  tasks:
    - name: Create db
      postgresql_db:
        name: '{{keycloak26.db.name}}'
        login_host: '{{keycloak26.db.host}}'
        login_user: '{{keycloak26.db.user}}' 
        login_password: '{{keycloak26.db.password}}'
        port: '{{keycloak26.db.port}}' 

# Install keycloak
- hosts: console
  vars:
    kube_config: '{{clusters.mz.kube_config}}'
    install_name: 'keycloak26'
    helm_chart: '{{charts_root}}/keycloak-26'
    is_template: true  
    helm_namespace: 'default'
    helm_values: '{{charts_root}}/keycloak-26/values.template.j2'
    helm_strings: 'keycloakPassword={{keycloak26.password}},db.password={{keycloak26.db.password}}'
  roles:
    - {role:  helm, tags: [keycloak26]}

  tasks:
    - name: Waiting for keycloak to install completely.
      pause:
        seconds: 10 

# Separate play for init to keep sequence of execution
#- hosts: console
#  roles:
#     - {role: keycloak-init, tags: [keycloak-init]}  


